# Credit Risk Resampling Techniques

In [106]:
import warnings
warnings.filterwarnings('ignore')

In [107]:
import numpy as np
import pandas as pd
from pathlib import Path
from collections import Counter

# Read the CSV into DataFrame

In [111]:
# Load the data
file_path = Path('lending_data.csv')
df = pd.read_csv(file_path)
df.head(30)

loan_size  interest_rate homeowner  borrower_income  debt_to_income  \
0     10700.0          7.672       own            52800        0.431818   
1      8400.0          6.692       own            43600        0.311927   
2      9000.0          6.963      rent            46100        0.349241   
3     10700.0          7.664       own            52700        0.430740   
4     10800.0          7.698  mortgage            53000        0.433962   
5     10100.0          7.438  mortgage            50600        0.407115   
6     10300.0          7.490  mortgage            51100        0.412916   
7      8800.0          6.857  mortgage            45100        0.334812   
8      9300.0          7.096       own            47400        0.367089   
9      9700.0          7.248      rent            48800        0.385246   
10     9300.0          7.085       own            47300        0.365751   
11     9200.0          7.015       own            46600        0.356223   
12     9200.0          7.043       own            46900        0.360341   
13     9400.0          7.101  mortgage            47400        0.367089   
14     8400.0          6.703  mortgage            43700        0.313501   
15     9400.0          7.136  mortgage            47700        0.371069   
16     8900.0          6.897       own            45500        0.340659   
17     8300.0          6.648  mortgage            43200        0.305556   
18     8000.0          6.539  mortgage            42100        0.287411   
19    10200.0          7.460      rent            50800        0.409449   
20     5200.0          5.326  mortgage            30700        0.022801   
21     9300.0          7.068       own            47100        0.363057   
22     7300.0          6.225       own            39200        0.234694   
23     9000.0          6.943       own            45900        0.346405   
24     8700.0          6.813       own            44700        0.328859   
25     8800.0          6.850  mortgage            45100        0.334812   
26     8400.0          6.700  mortgage            43700        0.313501   
27     7900.0          6.482       own            41600        0.278846   
28     9700.0          7.267  mortgage            49000        0.387755   
29     8400.0          6.700       own            43600        0.311927   

    num_of_accounts  derogatory_marks  total_debt loan_status  
0                 5                 1       22800    low_risk  
1                 3                 0       13600    low_risk  
2                 3                 0       16100    low_risk  
3                 5                 1       22700    low_risk  
4                 5                 1       23000    low_risk  
5                 4                 1       20600    low_risk  
6                 4                 1       21100    low_risk  
7                 3                 0       15100    low_risk  
8                 3                 0       17400    low_risk  
9                 4                 0       18800    low_risk  
10                3                 0       17300    low_risk  
11                3                 0       16600    low_risk  
12                3                 0       16900    low_risk  
13                3                 0       17400    low_risk  
14                3                 0       13700    low_risk  
15                3                 0       17700    low_risk  
16                3                 0       15500    low_risk  
17                2                 0       13200    low_risk  
18                2                 0       12100    low_risk  
19                4                 1       20800    low_risk  
20                0                 0         700    low_risk  
21                3                 0       17100    low_risk  
22                2                 0        9200    low_risk  
23                3                 0       15900    low_risk  
24                3                 0       14700    low_risk  
25            

# Split the Data into Training and Testing

In [117]:
# Create our features
X = df.drop(columns="loan_status")
X = pd.get_dummies(X)

# Create our target
target = ["loan_status"]
y = df.loc[:,target].copy()


In [119]:
y["loan_status"].value_counts()

low_risk     75036
high_risk     2500
Name: loan_status, dtype: int64

In [120]:
# Create X_train, X_test, y_train, y_test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)


## Data Pre-Processing

Scale the training and testing data using the `StandardScaler` from `sklearn`. Remember that when scaling the data, you only scale the features data (`X_train` and `X_testing`).

In [124]:
# Create the StandardScaler instance
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

In [127]:
# Scale the training and testing data

X_scaler = scaler.fit(X_train)
X_train_scaled = X_scaler.transform(X_train)
X_scaler2 = scaler.fit(X_test)
X_test_scaled = X_scaler2.transform(X_test)


# Simple Logistic Regression

In [128]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(solver='lbfgs', random_state=1)
model.fit(X_train, y_train)

LogisticRegression(random_state=1)

In [129]:
# Calculated the balanced accuracy score
from sklearn.metrics import balanced_accuracy_score
y_pred = model.predict(X_test)
balanced_accuracy_score(y_test, y_pred)

0.9520479254722232

In [130]:
# Display the confusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[  563,    56],
       [  102, 18663]], dtype=int64)

In [131]:
# Print the imbalanced classification report
from imblearn.metrics import classification_report_imbalanced
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.85      0.91      0.99      0.88      0.95      0.90       619
   low_risk       1.00      0.99      0.91      1.00      0.95      0.91     18765

avg / total       0.99      0.99      0.91      0.99      0.95      0.91     19384



# Oversampling

In this section, you will compare two oversampling algorithms to determine which algorithm results in the best performance. You will oversample the data using the naive random oversampling algorithm and the SMOTE algorithm. For each algorithm, be sure to complete the folliowing steps:

1. View the count of the target classes using `Counter` from the collections library. 
3. Use the resampled data to train a logistic regression model.
3. Calculate the balanced accuracy score from sklearn.metrics.
4. Print the confusion matrix from sklearn.metrics.
5. Generate a classication report using the `imbalanced_classification_report` from imbalanced-learn.

Note: Use a random state of 1 for each sampling algorithm to ensure consistency between tests

### Naive Random Oversampling

In [132]:
# Resample the training data with the RandomOversampler
from imblearn.over_sampling import RandomOverSampler

ros = RandomOverSampler(random_state=1)
X_resampled, y_resampled = ros.fit_resample(X_train, y_train)
Counter(y_resampled)

# View the count of target classes with Counter
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(solver='lbfgs', random_state=1)
model.fit(X_resampled, y_resampled)

LogisticRegression(random_state=1)

In [133]:
# Calculated the balanced accuracy score
from sklearn.metrics import balanced_accuracy_score

balanced_accuracy_score(y_test, y_pred)

0.9520479254722232

In [134]:
# Display the confusion matrix
from sklearn.metrics import confusion_matrix

y_pred = model.predict(X_test)
confusion_matrix(y_test, y_pred)

array([[  615,     4],
       [  116, 18649]], dtype=int64)

In [136]:
# Print the imbalanced classification report
from imblearn.metrics import classification_report_imbalanced

print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.84      0.99      0.99      0.91      0.99      0.99       619
   low_risk       1.00      0.99      0.99      1.00      0.99      0.99     18765

avg / total       0.99      0.99      0.99      0.99      0.99      0.99     19384



### SMOTE Oversampling

In [138]:
# Resample the training data with SMOTE
from imblearn.over_sampling import SMOTE

X_resampled, y_resampled = SMOTE(random_state=1, sampling_strategy=1.0).fit_resample(
    X_train, y_train
)
from collections import Counter

Counter(y_resampled)

# View the count of target classes with Counter


Counter({'loan_status': 1})

In [139]:
# Train the Logistic Regression model using the resampled data
model = LogisticRegression(solver='lbfgs', random_state=1)
model.fit(X_resampled, y_resampled)

LogisticRegression(random_state=1)

In [142]:
# Calculated the balanced accuracy score
predictions = model.predict(X_test_scaled)
acc_score= balanced_accuracy_score(y_test, predictions)

In [145]:
# Display the confusion matrix
print(confusion_matrix(y_test, predictions))
#display(cm_df)
print(f"Accuracy Score : {acc_score}")


[[  616     3]
 [ 7512 11253]]
Accuracy Score : 0.7974168645697335


In [147]:
# Print the imbalanced classification report
print("Classification Report")
print(classification_report_imbalanced(y_test, predictions))

Classification Report
                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.08      1.00      0.60      0.14      0.77      0.62       619
   low_risk       1.00      0.60      1.00      0.75      0.77      0.57     18765

avg / total       0.97      0.61      0.98      0.73      0.77      0.57     19384



# Undersampling

In this section, you will test an undersampling algorithm to determine which algorithm results in the best performance compared to the oversampling algorithms above. You will undersample the data using the Cluster Centroids algorithm and complete the folliowing steps:

1. View the count of the target classes using `Counter` from the collections library. 
3. Use the resampled data to train a logistic regression model.
3. Calculate the balanced accuracy score from sklearn.metrics.
4. Display the confusion matrix from sklearn.metrics.
5. Generate a classication report using the `imbalanced_classification_report` from imbalanced-learn.

Note: Use a random state of 1 for each sampling algorithm to ensure consistency between tests

In [148]:
# Resample the data using the ClusterCentroids resampler
# View the count of target classes with Counter

from imblearn.under_sampling import ClusterCentroids

cc = ClusterCentroids(random_state=1)
X_resampled, y_resampled = cc.fit_resample(X_train, y_train)

from collections import Counter

Counter(y_resampled)

Counter({'loan_status': 1})

In [149]:
# Train the Logistic Regression model using the resampled data
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(solver='lbfgs', random_state=1)
model.fit(X_resampled, y_resampled)

LogisticRegression(random_state=1)

In [150]:
# Calculate the balanced accuracy score
from sklearn.metrics import balanced_accuracy_score

balanced_accuracy_score(y_test, y_pred)

0.9936781215845847

In [151]:
# Display the confusion matrix
from sklearn.metrics import confusion_matrix
y_pred = model.predict(X_test)
confusion_matrix(y_test, y_pred)

array([[  606,    13],
       [  113, 18652]], dtype=int64)

In [152]:
# Print the imbalanced classification report
from imblearn.metrics import classification_report_imbalanced
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.84      0.98      0.99      0.91      0.99      0.97       619
   low_risk       1.00      0.99      0.98      1.00      0.99      0.97     18765

avg / total       0.99      0.99      0.98      0.99      0.99      0.97     19384



# Combination (Over and Under) Sampling

In this section, you will test a combination over- and under-sampling algorithm to determine if the algorithm results in the best performance compared to the other sampling algorithms above. You will resample the data using the SMOTEENN algorithm and complete the folliowing steps:

1. View the count of the target classes using `Counter` from the collections library. 
3. Use the resampled data to train a logistic regression model.
3. Calculate the balanced accuracy score from sklearn.metrics.
4. Display the confusion matrix from sklearn.metrics.
5. Generate a classication report using the `imbalanced_classification_report` from imbalanced-learn.

Note: Use a random state of 1 for each sampling algorithm to ensure consistency between tests

In [153]:
# Resample the training data with SMOTEENN
from imblearn.combine import SMOTEENN

smote_enn = SMOTEENN(random_state=0)
X_resampled, y_resampled = smote_enn.fit_resample(X_train, y_train)
Counter(y_resampled)

# View the count of target classes with Counter


Counter({'loan_status': 1})

In [154]:
# Train the Logistic Regression model using the resampled data
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(solver='lbfgs', random_state=1)
model.fit(X_resampled, y_resampled)

LogisticRegression(random_state=1)

In [155]:
# Calculate the balanced accuracy score
from sklearn.metrics import balanced_accuracy_score
balanced_accuracy_score(y_test, y_pred)

0.9864882676518989

In [156]:
# Display the confusion matrix
from sklearn.metrics import confusion_matrix
y_pred = model.predict(X_test)
confusion_matrix(y_test, y_pred)

array([[  615,     4],
       [  121, 18644]], dtype=int64)

In [157]:
# Print the imbalanced classification report
from imblearn.metrics import classification_report_imbalanced
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.84      0.99      0.99      0.91      0.99      0.99       619
   low_risk       1.00      0.99      0.99      1.00      0.99      0.99     18765

avg / total       0.99      0.99      0.99      0.99      0.99      0.99     19384



In [ ]:
Which model had the best balanced accuracy score?

print("The Undersampling had an accuracy score of 99%, making it the best model")

Which model had the best recall score?

print("They all had the same recall score of .99")

Which model had the best geometric mean score?

prinnt("They all had the same geo score of .99")

